import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WeirdThoughts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="class" enableSystem>
          <Toaster position="top-center" reverseOrder={false} />
          <Navbar />

          <div className="min-h-[80vh] max-w-[1400px] mx-auto">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
